{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TupleSections #-}
{-# LANGUAGE NoImplicitPrelude #-}

module HWM.Integrations.Toolchain.Nix (syncNixFile) where

import qualified Data.Text as T
import HWM.Core.Common (Name)
import HWM.Core.Formatting (Status, format, toCamelCase)
import HWM.Core.Options (Options (..))
import HWM.Core.Pkg (Pkg (..))
import HWM.Core.Version (Era (eraNixpkgs), formatNixGhc, selectEra)
import HWM.Domain.Config (Config (Config, cfgName, cfgRelease))
import HWM.Domain.ConfigT (ConfigT, Env (..))
import HWM.Domain.Environments (BuildEnvironment (..), getBuildEnvironment, getBuildEnvironments)
import HWM.Runtime.Files (syncFile)
import Relude

syncNixFile :: ConfigT Status
syncNixFile = do
  Config {..} <- asks config
  ops <- asks options
  benv <- getBuildEnvironment Nothing
  benvs <- filter buildNix <$> getBuildEnvironments
  releasePkgs <- pure ["hwm"] -- TODO: Get this from the release configuration once we support multiple artifacts.
  syncFile (optionsNix ops) (deriveFlakeNix releasePkgs (cfgName, benv) (map (cfgName,) benvs))

genName :: (Text, Text) -> Text
genName (name, subName) = toCamelCase (name <> T.toTitle subName <> "WorkspacePackages")

genNixName :: Context -> Text
genNixName (name, BuildEnvironment {..}) = genName (name, format buildName)

type Context = (Name, BuildEnvironment)

systems :: [Text]
systems =
  [ "x86_64-linux",
    "aarch64-linux",
    "x86_64-darwin",
    "aarch64-darwin"
  ]

deriveFlakeNix :: [Text] -> Context -> [Context] -> Text
deriveFlakeNix releasePkgs ctx@(projectName, benv) ctxs =
  T.unlines
    $ braces
      ( [ "description = \"A Haskell " <> projectName <> " workspace generated by HWM(Haskell Workspace Manager)\";",
          "inputs = {",
          "  nixpkgs.url = \"github:NixOS/nixpkgs/" <> eraNixpkgs (selectEra (buildGHC benv)) <> "\";",
          "};",
          "outputs = { self, nixpkgs }:"
        ]
          <> letBlock
            ( [ "supportedSystems = [ " <> T.intercalate " " (map show systems) <> " ];",
                "forAllSystems = nixpkgs.lib.genAttrs supportedSystems;"
              ]
                -- OVERLAY
                <> genOverlay ctx ctxs
            )
            -- PACKAGES
            ( forAllSystems "packages" artifactEngine (genPackages releasePkgs ctx ctxs)
                -- DEVSHELLS
                <> forAllSystems "devShells" [] (genDevShell True ctx <> concatMap (genDevShell False) ctxs)
                -- CHECKS
                <> ["checks = forAllSystems (system: self.packages.${system});"]
            )
            False
      )

-- OVERLAY
genOverlay :: Context -> [Context] -> [Text]
genOverlay static benvs =
  ["haskellOverlay = final: prev: {"]
    <> concatMap rendergOverlayItem benvs
    <> rendergOverlayStatic static
    <> ["};"]

rendergOverlayItem :: Context -> [Text]
rendergOverlayItem ctx@(_, BuildEnvironment {..}) =
  [ "  " <> genNixName ctx <> " = prev.haskell.packages." <> formatNixGhc buildGHC <> ".extend (hfinal: hprev: {"
  ]
    <> map (renderPackageDef renderPackageBody) buildPkgs
    <> ["  });"]

rendergOverlayStatic :: Context -> [Text]
rendergOverlayStatic (projectName, BuildEnvironment {..}) =
  [ "  " <> genName (projectName, "static") <> " = prev.pkgsStatic.haskell.packages." <> formatNixGhc buildGHC <> ".extend (hfinal: hprev: {"
  ]
    <> map (renderPackageDef (stripExecutables . renderPackageBody)) buildPkgs
    <> ["  });"]

stripExecutables :: (Semigroup a, IsString a) => a -> a
stripExecutables x = "prev.haskell.lib.justStaticExecutables (" <> x <> ")"

renderPackageDef :: (Pkg -> Text) -> Pkg -> Text
renderPackageDef body pkg = "    " <> format (pkgName pkg) <> " =  " <> body pkg <> ";"

renderPackageBody :: Pkg -> Text
renderPackageBody pkg = " hfinal.callCabal2nix \"" <> format (pkgName pkg) <> "\" ./" <> format (pkgDirPath pkg) <> " {}"

-- PACKAGES
genPackages :: [Text] -> Context -> [Context] -> [Text]
genPackages releasePkgs ctx@(projectName, defaultEnv) allEnvs =
  map (\pkg -> "default = pkgs." <> genNixName ctx <> "." <> format (pkgName pkg) <> ";") defaultPkg
    <> map (\pkg -> format (pkgName pkg) <> " = pkgs." <> genNixName ctx <> "." <> format (pkgName pkg) <> ";") (buildPkgs defaultEnv)
    <> concatMap genEnvPackages allEnvs
    <> concatMap allEnvPackages allEnvs
    <> genStaticPackages ctx
    <> map (genReleasePkg ctx) releasePkgs
    <> genReleaseGroup ctx releasePkgs
  where
    defaultPkg = filter ((projectName ==) . format . pkgName) (buildPkgs defaultEnv)

genPackage :: Text -> Text -> Pkg -> Text
genPackage overlay envName pkg = format (pkgName pkg) <> "-" <> envName <> " = pkgs." <> overlay <> "." <> format (pkgName pkg) <> ";"

genStaticPackages :: Context -> [Text]
genStaticPackages (projectname, env) = map (genPackage (genName (projectname, "static")) "static") (buildPkgs env)

genEnvPackages :: Context -> [Text]
genEnvPackages ctx@(_, env) = map (genPackage (genNixName ctx) (toCamelCase (format (buildName env)))) (buildPkgs env)

allEnvPackages :: Context -> [Text]
allEnvPackages ctx@(_, env) =
  genSymlinkJoin
    ("env-" <> toCamelCase (format (buildName env)) <> "-all")
    (format (buildName env) <> "-workspace")
    (map (\pkg -> "pkgs." <> genNixName ctx <> "." <> format (pkgName pkg)) (buildPkgs env))

genReleasePkg :: Context -> Text -> Text
genReleasePkg ctx name = name <> "-release = " <> genReleasePkgBody ctx name <> ";"

genReleasePkgBody :: Context -> Text -> Text
genReleasePkgBody ctx name = "mkReleaseArtifact \"" <> name <> "\" pkgs." <> genNixName ctx <> "." <> name <> " pkgs." <> genName (fst ctx, "static") <> "." <> name

genReleaseGroup :: Context -> [Text] -> [Text]
genReleaseGroup ctx pkgs =
  genSymlinkJoin
    "release"
    "release-artifacts"
    (map (\pkg -> "(" <> genReleasePkgBody ctx pkg <> ")") pkgs)

-- DEVSHELL
genDevShell :: Bool -> Context -> [Text]
genDevShell _ (_, BuildEnvironment {buildPkgs = []}) = [] -- Handle empty workspace
genDevShell isDefault ctx@(_, BuildEnvironment {..}) =
  [ name <> " = " <> devShellPackageName ctx <> ".shellFor {",
    "  packages = p: [ " <> renderPackageList buildPkgs <> " ];",
    "  buildInputs = with " <> devShellPackageName ctx <> "; ["
  ]
    <> map ("    " <>) libs
    <> [ "  ];",
         "};"
       ]
  where
    name = if isDefault then "default" else toCamelCase (format buildName)
    libs = ["cabal-install", "hlint"] <> ["stack" | buildStack] <> ["haskell-language-server" | buildHie]
    renderPackageList = T.intercalate " " . map (\pkg -> "p." <> format (pkgName pkg))

devShellPackageName :: Context -> Text
devShellPackageName ctx = "pkgs." <> genNixName ctx

artifactEngine :: [Text]
artifactEngine =
  [ "mkReleaseArtifact = pkgName: basePkg: staticPkg:",
    "  if pkgs.stdenv.hostPlatform.isLinux then",
    "    # LINUX: Return the fully static (musl), zero-dependency executable",
    "    staticPkg",
    "  else if pkgs.stdenv.hostPlatform.isDarwin then",
    "    # MACOS: We \"Bundle\" the dynamic dependencies since strict static is hard on Mac.",
    "    pkgs.runCommand \"${pkgName}-macos-bundle\" {",
    "      nativeBuildInputs = [ pkgs.macdylibbundler pkgs.darwin.autoSignDarwinBinariesHook ];",
    "    } ''",
    "      mkdir -p $out/bin",
    "",
    "      # 1. Copy the fast, dynamically linked binary (stripping docs/libs first)",
    "      cp ${pkgs.haskell.lib.justStaticExecutables basePkg}/bin/${pkgName} $out/bin/${pkgName}",
    "      chmod 755 $out/bin/${pkgName}",
    "",
    "      # 2. Run dylibbundler to pull all Nix store .dylibs into the local folder",
    "      dylibbundler -b --no-codesign -x $out/bin/${pkgName} -d $out/bin -p '@executable_path'",
    "",
    "      # 3. Re-sign the binary so Apple Silicon (M1/M2/M3) allows it to run natively",
    "      signDarwinBinariesInAllOutputs",
    "    ''",
    "  else",
    "    # Fallback for unexpected systems",
    "    basePkg;"
  ]

-- SYNTAX
forAllSystems :: Text -> [Text] -> [Text] -> [Text]
forAllSystems system lets body =
  [system <> " = forAllSystems (system:"]
    <> letBlock
      (["pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };"] <> lets)
      body
      True

letBlock :: [Text] -> [Text] -> Bool -> [Text]
letBlock h body end = ["let"] <> indent h <> ["in", "{"] <> indent body <> if end then ["});"] else ["};"]

braces :: [Text] -> [Text]
braces body = ["{"] <> indent body <> ["}"]

fun :: Text -> [Text] -> [Text]
fun name body = [name <> " {"] <> indent body <> ["};"]

genSymlinkJoin :: Text -> Text -> [Text] -> [Text]
genSymlinkJoin varName name pkgs =
  fun
    (varName <> " = pkgs.symlinkJoin")
    (["name = \"" <> name <> "\";", "paths = ["] <> indent pkgs <> ["];"])

indent :: [Text] -> [Text]
indent = map ("  " <>)