cabal-version: 1.12

--
-- see: https://github.com/sol/hpack

name:           bar
version:        0.1.1
synopsis:       Bar library
description:    Bar library for golden version tests.
category:       Development
author:         HWM
maintainer:     hwm@example.com
license:        MIT
license-file:   LICENSE
build-type:     Simple

library
  exposed-modules:
      Bar
  other-modules:
      Paths_bar
  hs-source-dirs:
      src
  build-depends:
      base >=4.7 && <5.0
  default-language: Haskell2010
