name: Setup
description: 'Installs Nix and configures magic caching for HWM'

runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build and Install HWM (Pure Nix)
      shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        nix profile install .
        hwm --version
