name: Setup
description: 'Installs Nix for Unix, or GHC/Cabal for Windows, and sets up HWM'

inputs:
  ghc:
    description: GHC Version (Used for Windows/Cabal fallback)
    required: false
    default: '9.6.3'

runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build and Install HWM (Pure Nix)
      shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        nix profile install .
        hwm --version
        hwm sync ci-nix