{
  description = "A Haskell hwm workspace generated by HWM(Haskell Workspace Manager)";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
  };
  outputs = { self, nixpkgs }:
    let
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
      haskellOverlay = final: prev: {
        hwmCiNixWorkspacePackages = prev.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = hfinal.callCabal2nix "hwm-golden" ./hwm-golden {};
          hwm = hfinal.callCabal2nix "hwm" ./hwm {};
        });
        hwmStableWorkspacePackages = prev.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = hfinal.callCabal2nix "hwm-golden" ./hwm-golden {};
          hwm = hfinal.callCabal2nix "hwm" ./hwm {};
        });
        hwmStaticWorkspacePackages = prev.pkgsStatic.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = hfinal.callCabal2nix "hwm-golden" ./hwm-golden {};
          hwm = hfinal.callCabal2nix "hwm" ./hwm {};
        });
      };
    in
    {
      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
        in
        {
          default = pkgs.hwmStableWorkspacePackages.hwm;
          hwm-golden = pkgs.hwmStableWorkspacePackages.hwm-golden;
          hwm = pkgs.hwmStableWorkspacePackages.hwm;
          hwm-golden-ciNix = pkgs.hwmCiNixWorkspacePackages.hwm-golden;
          hwm-ciNix = pkgs.hwmCiNixWorkspacePackages.hwm;
          env-ciNix-all = pkgs.symlinkJoin {
            name = "ci-nix-workspace";
            paths = [ 
              pkgs.hwmCiNixWorkspacePackages.hwm-golden
              pkgs.hwmCiNixWorkspacePackages.hwm
           ];
          };
          hwm-golden-stable = pkgs.hwmStableWorkspacePackages.hwm-golden;
          hwm-stable = pkgs.hwmStableWorkspacePackages.hwm;
          env-stable-all = pkgs.symlinkJoin {
            name = "stable-workspace";
            paths = [ 
              pkgs.hwmStableWorkspacePackages.hwm-golden
              pkgs.hwmStableWorkspacePackages.hwm
           ];
          };
          hwm-golden-static = pkgs.hwmStaticWorkspacePackages.hwm-golden;
          hwm-static = pkgs.hwmStaticWorkspacePackages.hwm;
        });
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
        in
        {
          default = pkgs.hwmStableWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmStableWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
          ciNix = pkgs.hwmCiNixWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmCiNixWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
          stable = pkgs.hwmStableWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmStableWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
        });
      checks = forAllSystems (system: self.packages.${system});
    };
}
