{
  description = "A Haskell hwm workspace generated by HWM (Haskell Workspace Manager)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
  };

  outputs = { self, nixpkgs }:
    let
      # 1. Define the architectures this flake supports natively.
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      
      # 2. Pure Nix helper function to generate attributes for all supported systems 
      #    (replacing the need for flake-utils).
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
      
      # 3. The Haskell Overlay: This overrides the default nixpkgs with our specific 
      #    GHC versions and local Cabal packages.
      haskellOverlay = final: prev: {
        
        # --- CI ENVIRONMENT (Fast, Dynamic Linking) ---
        hwmCiNixWorkspacePackages = prev.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = hfinal.callCabal2nix "hwm-golden" ./hwm-golden {};
          hwm = hfinal.callCabal2nix "hwm" ./hwm {};
        });
        
        # --- STABLE ENVIRONMENT ---
        hwmStableWorkspacePackages = prev.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = hfinal.callCabal2nix "hwm-golden" ./hwm-golden {};
          hwm = hfinal.callCabal2nix "hwm" ./hwm {};
        });
        
        # --- STATIC ENVIRONMENT (Slow, Fully Independent Binaries) ---
        # We use `pkgsStatic` for musl compilation on Linux.
        # We wrap it in `justStaticExecutables` to strip out heavy libraries/docs 
        # and keep only the tiny executable binary.
        hwmStaticWorkspacePackages = prev.pkgsStatic.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = prev.haskell.lib.justStaticExecutables (hfinal.callCabal2nix "hwm-golden" ./hwm-golden {});
          hwm = prev.haskell.lib.justStaticExecutables (hfinal.callCabal2nix "hwm" ./hwm {});
        });
      };
    in
    {
      packages = forAllSystems (system:
        let
          # Instantiate nixpkgs for the current system, applying our custom Haskell overlay
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
          
          # --- THE RELEASE ARTIFACT ENGINE ---
          # This function decides HOW to package the binary based on the OS running the build.
          mkReleaseArtifact = pkgName: basePkg: staticPkg:
            if pkgs.stdenv.hostPlatform.isLinux then
              # LINUX: Return the fully static (musl), zero-dependency executable
              staticPkg 
            else if pkgs.stdenv.hostPlatform.isDarwin then
              # MACOS: We "Bundle" the dynamic dependencies since strict static is hard on Mac.
              pkgs.runCommand "${pkgName}-macos-bundle" {
                nativeBuildInputs = [ pkgs.macdylibbundler pkgs.darwin.autoSignDarwinBinariesHook ];
              } ''
                mkdir -p $out/bin
                
                # 1. Copy the fast, dynamically linked binary (stripping docs/libs first)
                cp ${pkgs.haskell.lib.justStaticExecutables basePkg}/bin/${pkgName} $out/bin/${pkgName}
                chmod 755 $out/bin/${pkgName}
                
                # 2. Run dylibbundler to pull all Nix store .dylibs into the local folder
                dylibbundler -b --no-codesign -x $out/bin/${pkgName} -d $out/bin -p '@executable_path'
                
                # 3. Re-sign the binary so Apple Silicon (M1/M2/M3) allows it to run natively
                signDarwinBinariesInAllOutputs
              ''
            else 
              # Fallback for unexpected systems
              basePkg;
        in
        {
          # --- STANDARD CI TARGETS ---
          # Used for fast, local development. Executed via `nix build .#hwm`
          default = pkgs.hwmCiNixWorkspacePackages.hwm;
          hwm-golden = pkgs.hwmCiNixWorkspacePackages.hwm-golden;
          hwm = pkgs.hwmCiNixWorkspacePackages.hwm;
          hwm-golden-ciNix = pkgs.hwmCiNixWorkspacePackages.hwm-golden;
          hwm-ciNix = pkgs.hwmCiNixWorkspacePackages.hwm;
          
          # Group target: builds the entire CI workspace at once
          env-ciNix-all = pkgs.symlinkJoin {
            name = "ci-nix-workspace";
            paths = [ pkgs.hwmCiNixWorkspacePackages.hwm-golden pkgs.hwmCiNixWorkspacePackages.hwm ];
          };
          
          # --- STABLE TARGETS ---
          hwm-golden-stable = pkgs.hwmStableWorkspacePackages.hwm-golden;
          hwm-stable = pkgs.hwmStableWorkspacePackages.hwm;
          env-stable-all = pkgs.symlinkJoin {
            name = "stable-workspace";
            paths = [ pkgs.hwmStableWorkspacePackages.hwm-golden pkgs.hwmStableWorkspacePackages.hwm ];
          };
          
          # --- RAW STATIC TARGETS (For Linux Debugging) ---
          hwm-golden-static = pkgs.hwmStaticWorkspacePackages.hwm-golden;
          hwm-static = pkgs.hwmStaticWorkspacePackages.hwm;

          # --- FINAL PRODUCTION RELEASE TARGETS ---
          # Triggers the `mkReleaseArtifact` logic.
          # Run `nix build .#release` to get the portable folder tailored for your current OS.
          release-hwm = mkReleaseArtifact "hwm" pkgs.hwmCiNixWorkspacePackages.hwm pkgs.hwmStaticWorkspacePackages.hwm;
          
          # The master release collection. 
          # CI will zip the contents of this output folder to ship your software.
          release = pkgs.symlinkJoin {
            name = "hwm-release-artifacts";
            paths = [
              (mkReleaseArtifact "hwm" pkgs.hwmCiNixWorkspacePackages.hwm pkgs.hwmStaticWorkspacePackages.hwm)
              # If you ever want to release hwm-golden, simply add it here:
              # (mkReleaseArtifact "hwm-golden" pkgs.hwmCiNixWorkspacePackages.hwm-golden pkgs.hwmStaticWorkspacePackages.hwm-golden)
            ];
          };
        });

      # --- DEVELOPMENT ENVIRONMENTS ---
      # Used by `nix develop` or Direnv to provide a shell with GHC, Cabal, and HLS.
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
        in
        {
          default = pkgs.hwmCiNixWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmCiNixWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
          
          ciNix = pkgs.hwmCiNixWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmCiNixWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
          
          stable = pkgs.hwmStableWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmStableWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
        });

      # --- CHECKS ---
      # Run `nix flake check` to verify everything defined in `packages` compiles correctly.
      checks = forAllSystems (system: self.packages.${system});
    };
}