{
  description = "A Haskell hwm workspace generated by HWM(Haskell Workspace Manager)";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
  };
  outputs = { self, nixpkgs }:
    let
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
      haskellOverlay = final: prev: {
        hwmCiNixWorkspacePackages = prev.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = hfinal.callCabal2nix "hwm-golden" ./hwm-golden {};
          hwm = hfinal.callCabal2nix "hwm" ./hwm {};
        });
        hwmStableWorkspacePackages = prev.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = hfinal.callCabal2nix "hwm-golden" ./hwm-golden {};
          hwm = hfinal.callCabal2nix "hwm" ./hwm {};
        });
        hwmStaticWorkspacePackages = prev.pkgsStatic.haskell.packages.ghc96.extend (hfinal: hprev: {
          hwm-golden = hfinal.callCabal2nix "hwm-golden" ./hwm-golden {};
          hwm = hfinal.callCabal2nix "hwm" ./hwm {};
        });
      };
    in
    {
      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
          
          # --- THE NEW RELEASE LOGIC ---
          # We define a helper that takes a package name and creates a portable version
          mkReleaseArtifact = pkgName: basePkg: staticPkg:
            if pkgs.stdenv.hostPlatform.isLinux then
              staticPkg # LINUX: Use the pkgsStatic version
            else if pkgs.stdenv.hostPlatform.isDarwin then
              # MACOS: Bundle the dynamic version
              pkgs.runCommand "${pkgName}-macos-bundle" {
                nativeBuildInputs = [ pkgs.macdylibbundler pkgs.darwin.autoSignDarwinBinariesHook ];
              } ''
                mkdir -p $out/bin
                cp ${basePkg}/bin/${pkgName} $out/bin/${pkgName}
                chmod 755 $out/bin/${pkgName}
                dylibbundler -b --no-codesign -x $out/bin/${pkgName} -d $out/bin -p '@executable_path'
                signDarwinBinariesInAllOutputs
              ''
            else basePkg;

        in
        {
          # --- Your existing CI / Standard Packages ---
          default = pkgs.hwmCiNixWorkspacePackages.hwm;
          hwm-golden = pkgs.hwmCiNixWorkspacePackages.hwm-golden;
          hwm = pkgs.hwmCiNixWorkspacePackages.hwm;
          hwm-golden-ciNix = pkgs.hwmCiNixWorkspacePackages.hwm-golden;
          hwm-ciNix = pkgs.hwmCiNixWorkspacePackages.hwm;
          env-ciNix-all = pkgs.symlinkJoin {
            name = "ci-nix-workspace";
            paths = [ pkgs.hwmCiNixWorkspacePackages.hwm-golden pkgs.hwmCiNixWorkspacePackages.hwm ];
          };
          hwm-golden-stable = pkgs.hwmStableWorkspacePackages.hwm-golden;
          hwm-stable = pkgs.hwmStableWorkspacePackages.hwm;
          env-stable-all = pkgs.symlinkJoin {
            name = "stable-workspace";
            paths = [ pkgs.hwmStableWorkspacePackages.hwm-golden pkgs.hwmStableWorkspacePackages.hwm ];
          };
          
          # --- The raw Static targets (Mainly for Linux debugging) ---
          hwm-golden-static = pkgs.hwmStaticWorkspacePackages.hwm-golden;
          hwm-static = pkgs.hwmStaticWorkspacePackages.hwm;

          # --- THE NEW RELEASE TARGETS ---
          # These are what `hwm release artifacts` will call.
          # We use the mkReleaseArtifact helper to figure out if it should be Static or Bundled based on the OS.
          release-hwm = mkReleaseArtifact "hwm" pkgs.hwmCiNixWorkspacePackages.hwm pkgs.hwmStaticWorkspacePackages.hwm;
          
          # Group all release artifacts into one symlink
          release = pkgs.symlinkJoin {
            name = "hwm-release-artifacts";
            paths = [
              (mkReleaseArtifact "hwm" pkgs.hwmCiNixWorkspacePackages.hwm pkgs.hwmStaticWorkspacePackages.hwm)
              # Add hwm-golden here if it's meant to be released
            ];
          };
        });
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
        in
        {
          default = pkgs.hwmCiNixWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmCiNixWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
          ciNix = pkgs.hwmCiNixWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmCiNixWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
          stable = pkgs.hwmStableWorkspacePackages.shellFor {
            packages = p: [ p.hwm-golden p.hwm ];
            buildInputs = with pkgs.hwmStableWorkspacePackages; [
              cabal-install
              hlint
              stack
              haskell-language-server
            ];
          };
        });
      checks = forAllSystems (system: self.packages.${system});
    };
}
