{
  description = "A Haskell hwm workspace generated by HWM(Haskell Workspace Manager)";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
  };
  outputs = { self, nixpkgs }:
    let
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
      haskellOverlay = final: prev: {
            hwmWorkspacePackages = prev.haskell.packages.ghc96.extend (hfinal: hprev: {
              hwm = hfinal.callCabal2nix "hwm" ./hwm {};
            });
      };
    in
    {
      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
        in
        {
          hwm = pkgs.hwmWorkspacePackages.hwm;
          default = pkgs.hwmWorkspacePackages.hwm;
        });
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
        in
        {
          default = pkgs.hwmWorkspacePackages.shellFor {
            packages = p: [ p.hwm ];
            buildInputs = with pkgs.hwmWorkspacePackages; [
              cabal-install
              haskell-language-server
              hlint
            ];
          };
        });
    };
}
