{
  description = "A Haskell simple workspace generated by HWM(Haskell Workspace Manager)";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-22.05";
  };
  outputs = { self, nixpkgs }:
    let
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
      haskellOverlay = final: prev: {
            simpleWorkspacePackages = prev.haskell.packages.ghc810.extend (hfinal: hprev: {
              foo = hfinal.callCabal2nix "foo" ./foo {};
              bar = hfinal.callCabal2nix "bar" ./bar {};
            });
      };
    in
    {
      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
        in
        {
          foo = pkgs.simpleWorkspacePackages.foo;
          bar = pkgs.simpleWorkspacePackages.bar;
        });
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
        in
        {
          default = pkgs.simpleWorkspacePackages.shellFor {
            packages = p: [ p.foo p.bar ];
            buildInputs = with pkgs.simpleWorkspacePackages; [
              cabal-install
              haskell-language-server
              hlint
            ];
          };
        });
    };
}
