name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting an issue!
  
  - type: input
    id: version
    attributes:
      label: HWM Version
      description: Run `hwm version` or `stack exec -- hwm version`
      placeholder: "0.0.1"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the issue
    validations:
      required: true
  
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Run `hwm init`
        2. Edit hwm.yaml to...
        3. Run `hwm sync`
        4. Error occurs
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Config files, error messages, environment details
