name: hwm
version: 0.1.1
github: nalchevanidze/hwm
license: MIT
author: Daviti Nalchevanidze
category: Development
synopsis: Haskell Workspace Manager - Orchestrates Stack, Cabal, and HLS
maintainer: d.nalchevanidze@gmail.com
copyright: (c) 2026 Daviti Nalchevanidze
license-file: LICENSE
description: |
  HWM (Haskell Workspace Manager) manages multi-package Haskell projects by
  generating and synchronizing configuration files for Stack, Cabal, Hpack, and HLS
  from a single source of truth (hwm.yaml). It handles dependency management,
  build matrices across GHC versions, and coordinated package releases.
extra-source-files:
- README.md
- CHANGELOG.md
dependencies:
- Cabal                 >=  3.8         &&  <=  3.16.1.0
- Glob                  >=  0.10.1      &&  <=  0.10.2
- aeson                 >=  1.5.6.0     &&  <=  2.2.3.0
- ansi-terminal         >=  0.11.3      &&  <=  1.1.5
- async                 >   2.2.3       &&  <=  2.2.6
- base                  >=  4.7.0       &&  <   5.0.0
- base16-bytestring     >=  1.0.1.0     &&  <=  1.0.2.0
- bytestring            >=  0.10.4      &&  <=  0.12.2.0
- containers            >=  0.4.2.1     &&  <=  0.8
- cryptohash-sha256     >=  0.11.102.0  &&  <=  0.11.102.1
- directory             >=  1.0         &&  <=  1.3.10.1
- filepath              >=  1.1.0       &&  <=  1.5.5.0
- hpack                 >   0.34.4      &&  <=  0.39.1
- modern-uri            >=  0.3.4.1     &&  <=  0.3.6.1
- mtl                   >   2.0.0       &&  <   2.6.0
- optparse-applicative  >=  0.16.1.0    &&  <=  0.19.0.0
- process               >=  1.0.0       &&  <   2.0.0
- relude                >=  0.7.0.0     &&  <=  1.2.2.2
- req                   >=  3.9.0       &&  <=  3.13.4
- stm                   >=  2.4         &&  <   2.6.0
- text                  >=  1.2.3       &&  <   3.0.0
- time                  >=  1.9.2       &&  <   2.0.0
- transformers          >=  0.5.6       &&  <   0.7.0
- typed-process         >=  0.2.6.1     &&  <=  0.2.13.0
- unordered-containers  >=  0.2.14.0    &&  <=  0.2.21
- yaml                  >=  0.11.5.0    &&  <=  0.11.11.2
- zip-archive           >=  0.4.1       &&  <=  0.4.3.2
library:
  source-dirs: src
  ghc-options: -Wall
executables:
  hwm:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall
    dependencies:
    - hwm  >=  0.1.0  &&  <  0.2.0
