{
  description = "A Haskell simple workspace generated by HWM(Haskell Workspace Manager)";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-22.05";
  };
  outputs = { self, nixpkgs }:
  let
    supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
    forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
    haskellOverlay = final: prev: {
      simpleFooWorkspacePackages = prev.haskell.packages.ghc810.extend (hfinal: hprev: {
        foo = hfinal.callCabal2nix "foo" ./foo {};
        bar = hfinal.callCabal2nix "bar" ./bar {};
      });
    };
  in
  {
    packages = forAllSystems (system:
    let
      pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
      mkReleaseArtifact = pkgName: basePkg: staticPkg:
        if pkgs.stdenv.hostPlatform.isLinux then
          # LINUX: Return the fully static (musl), zero-dependency executable
          staticPkg
        else if pkgs.stdenv.hostPlatform.isDarwin then
          # MACOS: We "Bundle" the dynamic dependencies since strict static is hard on Mac.
          pkgs.runCommand "${pkgName}-macos-bundle" {
            nativeBuildInputs = [ pkgs.macdylibbundler pkgs.darwin.autoSignDarwinBinariesHook ];
          } ''
            mkdir -p $out/bin
      
            # 1. Copy the fast, dynamically linked binary (stripping docs/libs first)
            cp ${pkgs.haskell.lib.justStaticExecutables basePkg}/bin/${pkgName} $out/bin/${pkgName}
            chmod 755 $out/bin/${pkgName}
      
            # 2. Run dylibbundler to pull all Nix store .dylibs into the local folder
            dylibbundler -b --no-codesign -x $out/bin/${pkgName} -d $out/bin -p '@executable_path'
      
            # 3. Re-sign the binary so Apple Silicon (M1/M2/M3) allows it to run natively
            signDarwinBinariesInAllOutputs
          ''
        else
          # Fallback for unexpected systems
          basePkg;
    in
    {
      foo = pkgs.simpleFooWorkspacePackages.foo;
      bar = pkgs.simpleFooWorkspacePackages.bar;
      foo-foo = pkgs.simpleFooWorkspacePackages.foo;
      bar-foo = pkgs.simpleFooWorkspacePackages.bar;
      env-foo-all = pkgs.symlinkJoin {
        name = "foo-workspace";
        paths = [
          pkgs.simpleFooWorkspacePackages.foo
          pkgs.simpleFooWorkspacePackages.bar
        ];
      };
    });
    devShells = forAllSystems (system:
    let
      pkgs = import nixpkgs { inherit system; overlays = [ haskellOverlay ]; };
    in
    {
      default = pkgs.simpleFooWorkspacePackages.shellFor {
        packages = p: [ p.foo p.bar ];
        buildInputs = with pkgs.simpleFooWorkspacePackages; [
          cabal-install
          hlint
          stack
          haskell-language-server
        ];
      };
      foo = pkgs.simpleFooWorkspacePackages.shellFor {
        packages = p: [ p.foo p.bar ];
        buildInputs = with pkgs.simpleFooWorkspacePackages; [
          cabal-install
          hlint
          stack
          haskell-language-server
        ];
      };
    });
    checks = forAllSystems (system: self.packages.${system});
  };
}
