name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        run: hwm build --fast
      - name: Test
        run: hwm test --fast

  archive:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu, macOS]
    name: Artifact ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test Archiving
        run: hwm release artifacts

  archive-windows:
    name: Artifact Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-windows
      - name: Test Archiving
        run: hwm release artifacts

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: curl -sSL https://raw.githubusercontent.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL "https://raw.githubusercontent.com/nalchevanidze/hwm/main/scripts/format.sh" | bash -s

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
