name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Build
        shell: bash
        run: hwm build --fast

      - name: Test
        shell: bash
        run: hwm test --fast

  artifacts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    name: Artifact ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-artifacts

      - name: Test Archiving
        shell: bash
        run: hwm release artifacts hwm

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: curl -sSL https://raw.githubusercontent.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

      - name: Format
        run: curl -fsSL "https://raw.githubusercontent.com/nalchevanidze/hwm/main/scripts/format.sh" | bash -s

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
